# Generated by Django 4.0 on 2023-08-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_familly', models.CharField(max_length=100)),
                ('student_Age', models.IntegerField(default=0)),
                ('student_fathername', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=100)),
                ('student_password', models.CharField(max_length=100)),
                ('student_birthdate', models.DateTimeField(auto_now_add=True)),
                ('student_creatdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
