# Generated by Django 4.0 on 2023-08-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_username_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_password',
        ),
    ]
