# Generated by Django 4.0 on 2023-08-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_student_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_birthdate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_creatdate',
        ),
    ]
