# Generated by Django 4.0 on 2023-08-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_student_student_birthdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='USERNAME_FIELD',
            new_name='student_username',
        ),
    ]
