# Generated by Django 4.0 on 2023-08-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_username_field_student_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='123', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_username',
            field=models.CharField(max_length=100),
        ),
    ]
