# Generated by Django 4.0 on 2023-08-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_student_student_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
